name: myportfolio
description: A new Flutter project.
version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.2
  animated_text_kit: ^2.0.0
  google_fonts: ^0.3.3
  url_launcher: ^5.4.1
  community_material_icon: ^3.5.95

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  # assets:
  #   - assets/